// autogenerated at 2024-07-20T13:48:45.4459180+02:00

interface IHLoginRequest {
    email: string | null;
    password: string | null;
}

interface IHLoginResponse {
    status: number | null;
    nameIdentifier: string | null;
    name: string | null;
}

interface IHRegisterRequest {
    email: string | null;
    password: string | null;
    repeat: string | null;
}

