// autogenerated at 2024-07-14T10:54:44.3112126+02:00

import { baseUrl } from "$api/_url";

/**
* function auth.register_with_password(
*     _email text,
*     _password text,
*     _repeat text
* )
* returns json
* 
* @remarks
* comment on function auth.register_with_password is 'HTTP POST /auth/register
* anonymous';
* 
* @see FUNCTION auth.register_with_password
*/
export async function hRegister(
    request: IHRegisterRequest,
    parseUrl: (url: string) => string = url=>url,
    parseRequest: (request: RequestInit) => RequestInit = request=>request
) : Promise<{status: number, response: string}> {
    const response = await fetch(parseUrl(baseUrl + "/auth/register"), parseRequest({
        method: "POST",
        body: JSON.stringify(request)
    }));
    return {
        status: response.status,
        response: await response.text()
    };
}
