// autogenerated at 2024-07-21T13:19:04.5704513+02:00

interface IHLoginRequest {
    email: string | null;
    password: string | null;
}

interface IHLoginResponse {
    status: number | null;
    nameIdentifier: string | null;
    name: string | null;
}

interface IHRegisterRequest {
    email: string | null;
    password: string | null;
    repeat: string | null;
}

