@host=http://localhost:5000

// function auth.login_with_password(
//     _email text,
//     _password text
// )
// returns table(
//     status integer,
//     name_identifier text,
//     name text
// )
//
// comment on function auth.login_with_password is 'HTTP POST /auth/login
// anonymous';
POST {{host}}/auth/login
content-type: application/json

{
    "email": "ABC",
    "password": "XYZ"
}

###

// function auth.register_with_password(
//     _email text,
//     _password text,
//     _repeat text
// )
// returns json
//
// comment on function auth.register_with_password is 'HTTP POST /auth/register
// anonymous';
POST {{host}}/auth/register
content-type: application/json

{
    "email": "ABC",
    "password": "XYZ",
    "repeat": "IJK"
}

###

