@host=http://localhost:5000

// function pages.admin(
//     _user_id text DEFAULT NULL::text,
//     _user_name text DEFAULT NULL::text,
//     _user_roles text[] DEFAULT NULL::text[],
//     _permissions text[] DEFAULT NULL::text[],
//     _headers json DEFAULT NULL::json
// )
// returns text
//
// comment on function pages.admin is 'HTTP GET /admin
// Content-Type: text/html
// allow-anonymous';
GET {{host}}/admin?userId=ABC&userName=XYZ&userRoles=IJK&userRoles=ABC&userRoles=XYZ&permissions=ABC&permissions=XYZ&permissions=IJK&headers=%7B%7D

###

// function pages.index(
//     _user_id text DEFAULT NULL::text,
//     _user_name text DEFAULT NULL::text,
//     _user_roles text[] DEFAULT NULL::text[],
//     _permissions text[] DEFAULT NULL::text[],
//     _headers json DEFAULT NULL::json
// )
// returns text
//
// comment on function pages.index is 'HTTP GET /
// Content-Type: text/html
// allow-anonymous';
GET {{host}}/?userId=ABC&userName=XYZ&userRoles=IJK&userRoles=ABC&userRoles=XYZ&permissions=ABC&permissions=XYZ&permissions=IJK&headers=%7B%7D

###

